apiVersion: apps/v1
kind: Deployment
metadata:
  name: board
  labels:
    app: board
    tier: backend
    version: v1
spec:
  selector:
    matchLabels:
      app: board
  replicas: 2
  template:
    metadata:
      labels:
        app: board
    spec:
      containers:
      - name: board
        image: nitrix/nullboard
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: board
spec:
  selector:
    app: board
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: board
spec:
  tls:
  - hosts:
      - board.nitrix.me
    secretName: nitrixme-tls
  rules:
  - host: board.nitrix.me
    http:
      paths:
      - path: /
        backend:
          serviceName: board
          servicePort: 80