apiVersion: v1
kind: Namespace
metadata:
  name: nitrixme
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: justin
  namespace: nitrixme
  labels:
    app: justin
    tier: backend
    version: v1
spec:
  selector:
    matchLabels:
      app: justin
  replicas: 2
  template:
    metadata:
      labels:
        app: justin
    spec:
      containers:
      - name: justin
        image: nitrix/justin
        ports:
        - containerPort: 8080
        livenessProbe:
          initialDelaySeconds: 2
          periodSeconds: 5
          httpGet:
            path: /
            port: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: justin
  namespace: nitrixme
spec:
  selector:
    app: justin
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: justin
  namespace: nitrixme
spec:
  tls:
  - hosts:
      - justin.nitrix.me
    secretName: nitrixme-tls
  rules:
  - host: justin.nitrix.me
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: justin
            port:
              number: 8080