apiVersion: v1
kind: Namespace
metadata:
  name: nitrixme
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kanban
  namespace: nitrixme
  labels:
    app: kanban
    tier: backend
    version: v1
spec:
  selector:
    matchLabels:
      app: kanban
  replicas: 1
  template:
    metadata:
      labels:
        app: kanban
    spec:
      containers:
      - name: kanban
        image: nitrix/kanban:v0.0.1
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /opt/data
          name: kanban-data
        env:
        - name: USERNAME
          value: "nitrix"
        - name: PASSWORD
          valueFrom:
              secretKeyRef:
                name: kanban
                key: PASSWORD
        - name: FEATURE_STAY_LOGGED
          value: "true"
      volumes:
      - name: kanban-data
        hostPath:
          path: /home/kanban
---
apiVersion: v1
kind: Service
metadata:
  name: kanban
  namespace: nitrixme
spec:
  selector:
    app: kanban
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kanban
  namespace: nitrixme
spec:
  tls:
  - hosts:
      - kanban.nitrix.me
    secretName: nitrixme-tls
  rules:
  - host: kanban.nitrix.me
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kanban
            port:
              number: 80