apiVersion: v1
kind: Namespace
metadata:
  name: nitrixme
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft
  namespace: nitrixme
  labels:
    app: minecraft
    tier: backend
    version: v1
spec:
  selector:
    matchLabels:
      app: minecraft
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: minecraft
    spec:
      containers:
      - name: minecraft
        image: itzg/minecraft-server
        imagePullPolicy: Always
        ports:
        - containerPort: 25565
          name: minecraft-tcp
          protocol: TCP
        env:
        - name: EULA
          value: "TRUE"
        volumeMounts:
        - mountPath: /data
          name: data
      volumes:
      - name: data
        hostPath:
          path: /home/minecraft
---
apiVersion: v1
kind: Service
metadata:
  name: minecraft-tcp
  namespace: nitrixme
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  selector:
    app: minecraft
  type: LoadBalancer
  ports:
    - port: 25565
      targetPort: 25565
      protocol: TCP
      name: minecraft-tcp