apiVersion: v1
kind: Namespace
metadata:
  name: nitrixme
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: senko
  namespace: nitrixme
  labels:
    app: senko
    tier: backend
    version: v1
spec:
  selector:
    matchLabels:
      app: senko
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: senko
    spec:
      containers:
      - name: senko
        image: nitrix/senko
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /opt/senko/config
          name: senko-config
        env:
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: "config/senko-google-cloud-credentials.json"
          - name: DISCORD_TOKEN
            valueFrom:
              secretKeyRef:
                name: senko
                key: DISCORD_TOKEN
          - name: WOLFRAM_TOKEN
            valueFrom:
              secretKeyRef:
                name: senko
                key: WOLFRAM_TOKEN
          - name: EXTERNAL_URL_PREFIX
            value: "https://senko.nitrix.me"
#        livenessProbe:
#          initialDelaySeconds: 2
#          periodSeconds: 5
#          httpGet:
#            path: /downloads
#            port: 80
      volumes:
      - name: senko-config
        hostPath:
          path: /home/senko/config
---
apiVersion: v1
kind: Service
metadata:
  name: senko
  namespace: nitrixme
spec:
  selector:
    app: senko
  ports:
    - port: 80
      targetPort: 80
#---
#apiVersion: networking.k8s.io/v1
#kind: Ingress
#metadata:
#  name: senko
#  namespace: nitrixme
#spec:
#  tls:
#  - hosts:
#      - senko.nitrix.me
#    secretName: nitrixme-tls
#  rules:
#  - host: senko.nitrix.me
#    http:
#      paths:
#      - path: /
#        pathType: Prefix
#        backend:
#          service:
#            name: senko
#            port:
#              number: 80