apiVersion: apps/v1
kind: Deployment
metadata:
  name: torrent
  labels:
    app: torrent
    tier: backend
    version: v1
spec:
  selector:
    matchLabels:
      app: torrent
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: torrent
    spec:
      containers:
      - name: torrent
        image: linuxserver/qbittorrent
        ports:
        - containerPort: 8080
        - containerPort: 6881
        volumeMounts:
          - mountPath: /config
            name: torrent-config
          - mountPath: /downloads
            name: torrent-downloads
      volumes:
        - name: torrent-config
          hostPath:
            path: /home/torrent/config
        - name: torrent-downloads
          hostPath:
            path: /home/torrent/downloads
---
apiVersion: v1
kind: Service
metadata:
  name: torrent
spec:
  selector:
    app: torrent
  ports:
    - port: 80
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: torrent-through
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  selector:
    app: torrent
  type: LoadBalancer
  ports:
    - port: 6881
      targetPort: 6881
      protocol: TCP
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: torrent
spec:
  tls:
  - hosts:
      - torrent.nitrix.me
    secretName: nitrixme-tls
  rules:
  - host: torrent.nitrix.me
    http:
      paths:
      - path: /
        backend:
          serviceName: torrent
          servicePort: 80