apiVersion: v1
kind: Namespace
metadata:
  name: nitrixme
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: torrent
  namespace: nitrixme
  labels:
    app: torrent
    tier: backend
    version: v1
spec:
  selector:
    matchLabels:
      app: torrent
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: torrent
    spec:
      containers:
      - name: torrent
        image: linuxserver/transmission
        ports:
        - containerPort: 9091
        - containerPort: 51413
          name: traffic-tcp
          protocol: TCP
        - containerPort: 51413
          name: traffic-udp
          protocol: UDP
        volumeMounts:
          - mountPath: /config
            name: torrent-config
          - mountPath: /downloads
            name: torrent-downloads
          - mountPath: /watch
            name: torrent-watch
        env:
          - name: USER
            value: nitrix
          - name: PASS
            valueFrom:
              secretKeyRef:
                name: torrent
                key: PASS
      volumes:
        - name: torrent-config
          hostPath:
            path: /home/torrent/config
        - name: torrent-downloads
          hostPath:
            path: /home/torrent/downloads
        - name: torrent-watch
          hostPath:
            path: /home/torrent/watch
---
apiVersion: v1
kind: Service
metadata:
  name: torrent
  namespace: nitrixme
spec:
  selector:
    app: torrent
  ports:
    - port: 80
      targetPort: 9091
---
apiVersion: v1
kind: Service
metadata:
  name: torrent-through-tcp
  namespace: nitrixme
spec:
  selector:
    app: torrent
  type: NodePort
  ports:
    - port: 51413
      targetPort: 51413
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: torrent-through-udp
  namespace: nitrixme
spec:
  selector:
    app: torrent
  type: NodePort
  ports:
    - port: 51413
      targetPort: 51413
      protocol: UDP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: torrent
  namespace: nitrixme
spec:
  tls:
  - hosts:
      - torrent.nitrix.me
    secretName: nitrixme-tls
  rules:
  - host: torrent.nitrix.me
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: torrent
            port:
              number: 80