apiVersion: v1
kind: Namespace
metadata:
  name: nitrixme
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tracker
  namespace: nitrixme
  labels:
    app: tracker
    tier: backend
    version: v1
spec:
  selector:
    matchLabels:
      app: tracker
  replicas: 1
  template:
    metadata:
      labels:
        app: tracker
    spec:
      containers:
      - name: tracker
        image: lednerb/opentracker-docker
        ports:
        - containerPort: 6969
        livenessProbe:
          initialDelaySeconds: 2
          periodSeconds: 5
          httpGet:
            path: /stats
            port: 6969
---
apiVersion: v1
kind: Service
metadata:
  name: tracker
  namespace: nitrixme
spec:
  selector:
    app: tracker
  ports:
    - port: 80
      targetPort: 6969
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tracker
  namespace: nitrixme
spec:
  tls:
  - hosts:
      - tracker.nitrix.me
    secretName: nitrixme-tls
  rules:
  - host: tracker.nitrix.me
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: tracker
            port:
              number: 80