apiVersion: v1
kind: Namespace
metadata:
  name: nitrixme
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: www
  namespace: nitrixme
  labels:
    app: www
    tier: backend
spec:
  selector:
    matchLabels:
      app: www
  replicas: 2
  template:
    metadata:
      labels:
        app: www
    spec:
      containers:
      - name: www
        image: nitrix/nitrixme
        ports:
        - containerPort: 8080
        livenessProbe:
          initialDelaySeconds: 2
          periodSeconds: 5
          httpGet:
            path: /
            port: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: www
  namespace: nitrixme
spec:
  selector:
    app: www
  ports:
    - port: 80
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: www
  namespace: nitrixme
spec:
  tls:
  - hosts:
      - nitrix.me
    secretName: nitrixme-tls
  rules:
  - host: nitrix.me
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: www
              port:
                number: 80