version: '3.3'

services:
    hello:
        image: "crccheck/hello-world"
        deploy:
            replicas: 2
        healthcheck:
            test: "wget --quiet --tries=1 --spider http://localhost:8000/ || exit 1" 
            interval: 10s
            timeout: 5s
            retries: 5

    nginx:
        image: "nginx"
        volumes:
            - type: bind
              source: ./conf/nginx/nginx.conf
              target: /etc/nginx/nginx.conf
              read_only: true
            - type: bind
              source: ./conf/nginx/ssl
              target: /etc/nginx/ssl
              read_only: true
        ports:
            - "443:443"

    znc:
        image: "linuxserver/znc"
        volumes:
            - /home/znc:/config
        deploy:
            replicas: 1
            placement:
                constraints:
                    - node.hostname == s1
        ports:
            - 7000:6501

    tracker:
        image: "lednerb/opentracker-docker"