version: '3.3'
services:
    hello:
        image: "crccheck/hello-world"
        deploy:
            replicas: 2
        healthcheck:
            test: "wget --quiet --tries=1 --spider http://localhost:8000/ || exit 1" 
            interval: 10s
            timeout: 5s
            retries: 5

    nginx:
        image: "nginx"
        volumes:
            - type: bind
              source: ./conf/nginx/nginx.conf
              target: /etc/nginx/nginx.conf
              read_only: true
            - type: bind
              source: ./conf/nginx/ssl
              target: /etc/nginx/ssl
              read_only: true
        ports:
            - "9080:80"
            - "9443:443"