version: '3.3'

services:
    hello:
        image: "crccheck/hello-world"
        deploy:
            replicas: 2
        healthcheck:
            test: "wget --quiet --tries=1 --spider http://localhost:8000/ || exit 1" 
            interval: 10s
            timeout: 5s
            retries: 5

    nginx:
        image: "nginx"
        volumes:
            - type: bind
              source: ./conf/nginx/nginx.conf
              target: /etc/nginx/nginx.conf
              read_only: true
            - type: bind
              source: ./conf/nginx/ssl
              target: /etc/nginx/ssl
              read_only: true
        ports:
            - "443:443"

    znc:
        image: "linuxserver/znc"
        volumes:
            - /home/znc:/config
        deploy:
            placement:
                constraints:
                    - node.hostname == s1
        ports:
            - 7000:6501
            
    senko:
        image: "nitrix/senko:latest"
        volumes:
            - /home/senko/config:/go/config
            - /home/senko/downloads:/go/downloads
        deploy:
            placement:
                constraints:
                    - node.hostname == s1
        env_file:
            - ./conf/senko.env

    tracker:
        image: "lednerb/opentracker-docker"