apiVersion: batch/v1
kind: CronJob
metadata:
  name: backup
spec:
  schedule: "@hourly"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: backup
              image: busybox
              args:
                - /bin/sh
                - -c
                - date; echo Hello World!
          restartPolicy: OnFailure