apiVersion: v1
kind: Namespace
metadata:
  name: nitrixme
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: drop
  namespace: nitrixme
  labels:
    app: drop
    tier: backend
    version: v1
spec:
  selector:
    matchLabels:
      app: drop
  replicas: 2
  template:
    metadata:
      labels:
        app: drop
    spec:
      containers:
      - name: drop
        image: ghcr.io/linuxserver/snapdrop
        ports:
        - containerPort: 80
        livenessProbe:
          initialDelaySeconds: 2
          periodSeconds: 5
          httpGet:
            path: /
            port: 80
---
apiVersion: v1
kind: Service
metadata:
  name: drop
  namespace: nitrixme
spec:
  selector:
    app: drop
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: drop
  namespace: nitrixme
spec:
  tls:
  - hosts:
      - drop.nitrix.me
    secretName: nitrixme-tls
  rules:
  - host: drop.nitrix.me
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: drop
            port:
              number: 80