apiVersion: v1
kind: Namespace
metadata:
  name: nitrixme
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: factorio
  namespace: nitrixme
  labels:
    app: factorio
    tier: backend
    version: v1
spec:
  selector:
    matchLabels:
      app: factorio
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: factorio
    spec:
      containers:
      - name: factorio
        image: factoriotools/factorio
        imagePullPolicy: Always
        ports:
        - containerPort: 27015
          name: factorio-tcp
          protocol: TCP
        - containerPort: 34197
          name: factorio-udp
          protocol: UDP
        volumeMounts:
        - mountPath: /factorio
          name: data
      volumes:
      - name: data
        hostPath:
          path: /home/factorio
---
apiVersion: v1
kind: Service
metadata:
  name: factorio-tcp
  namespace: nitrixme
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  selector:
    app: factorio
  type: LoadBalancer
  ports:
    - port: 27015
      targetPort: 27015
      protocol: TCP
      name: factorio-tcp
---
apiVersion: v1
kind: Service
metadata:
  name: factorio-udp
  namespace: nitrixme
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  selector:
    app: factorio
  type: LoadBalancer
  ports:
    - port: 34197
      targetPort: 34197
      protocol: UDP
      name: factorio-udp