name: deploy
on:
    push:
        branches:
            - master
jobs:
    setup:
        name: Deploying to Docker Swarm
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        
        - name: Writing secrets to files
          env:
            NITRIX_ME_CRT: ${{ secrets.NITRIX_ME_CRT }}
            NITRIX_ME_PEM: ${{ secrets.NITRIX_ME_PEM }}
          shell: bash
          run: |
            echo $NITRIX_ME_CRT > conf/ssl/nitrix.me.crt
            echo $NITRIX_ME_PEM > conf/ssl/nitrix.me.pem
        
        - name: Test connection to swarm server
          shell: bash
          env:
            SWARM_SSH_IP: ${{ secrets.SWARM_SSH_IP }}
            SWARM_SSH_USER: ${{ secrets.SWARM_SSH_USER }}
            SWARM_SSH_KEY: ${{ secrets.SWARM_SSH_KEY }}
          run: |
            eval `ssh-agent -s`
            echo "$SWARM_SSH_KEY" | ssh-add -
            ssh -o StrictHostKeyChecking=no $SWARM_SSH_USER@$SWARM_SSH_IP ls