name: deploy
on:
    push:
        branches:
            - master
jobs:
    setup:
        name: Deploying to Docker Swarm
        runs-on: ubuntu-latest
        steps:
        - name: Writing nginx SSL keys
          env:
            BANANA: ${{ secrets.BANANA }}
          shell: bash
          run: |
            touch foo && echo $BANANA
    setup2:
        name: Listing files
        runs-on: ubuntu-latest
        steps:
        - name: ls command
          shell: bash
          run: ls