name: deploy
on:
    push:
        branches:
            - master
jobs:
    setup:
        name: Deploying the infrastructure
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        
        - name: Obtaining SSL certificates
          env:
            NITRIX_ME_CRT: ${{ secrets.NITRIX_ME_CRT }}
            NITRIX_ME_PEM: ${{ secrets.NITRIX_ME_PEM }}
          shell: bash
          run: |
            echo $NITRIX_ME_CRT > conf/nginx/ssl/nitrix.me.crt
            echo $NITRIX_ME_PEM > conf/nginx/ssl/nitrix.me.pem

        - name: Updating prod stack
          shell: bash
          env:
            SWARM_SSH_IP: ${{ secrets.SWARM_SSH_IP }}
            SWARM_SSH_USER: ${{ secrets.SWARM_SSH_USER }}
            SWARM_SSH_KEY: ${{ secrets.SWARM_SSH_KEY }}
          run: |
            eval `ssh-agent -s`
            echo "$SWARM_SSH_KEY" | ssh-add -
            mkdir -p ~/.ssh
            ssh-keyscan -t rsa $SWARM_SSH_IP >> ~/.ssh/known_hosts
            rsync --exclude .git --inplace -r . $SWARM_SSH_USER@$SWARM_SSH_IP:/tmp/infrastructure --delete
            ssh $SWARM_SSH_USER@$SWARM_SSH_IP docker stack deploy --prune -c /tmp/infrastructure/docker-compose.yml prod
            ssh $SWARM_SSH_USER@$SWARM_SSH_IP docker ps -q -f name=prod_nginx | xargs -I % bash -c 'docker exec % nginx -s reload'